import { StyleSheet } from "react-native";

const MAUVE = "#936D9A";

export const pg = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8FAFC" },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 40,
    alignItems: "center",
  },
  content: { width: "100%", maxWidth: 1000 },

  // Header
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    alignItems: "center",
    justifyContent: "center",
  },
  title: { fontSize: 24, fontWeight: "800", color: "#0F172A" },
  subtitle: { fontSize: 13, color: "#64748B", marginTop: 2 },

  // Layout
  grid: { flexDirection: "row", flexWrap: "wrap", alignItems: "flex-start" },
  sectionLabel: {
    fontSize: 13,
    fontWeight: "800",
    color: "#64748B",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginTop: 8,
    marginBottom: 12,
  },

  // Category card (Explore)
  catCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  catTop: { flexDirection: "row", alignItems: "center", gap: 12 },
  catIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  catTitle: { flex: 1, fontSize: 17, fontWeight: "800", color: "#0F172A" },
  catCount: {
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 10,
    backgroundColor: "#F1F5F9",
  },
  catCountText: { fontSize: 11, fontWeight: "700", color: "#475569" },
  catDesc: { fontSize: 13.5, color: "#64748B", lineHeight: 20, marginTop: 12 },
  catCta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 14,
    alignSelf: "flex-start",
  },
  catCtaText: { fontSize: 14, fontWeight: "800", color: MAUVE },

  // Enrolled card
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    overflow: "hidden",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  cardPast: { opacity: 0.85 },
  poster: { width: "100%", height: 120, backgroundColor: "#E2E8F0" },
  cardBody: { padding: 16 },
  cardHead: { flexDirection: "row", gap: 14 },
  dateBlock: {
    width: 50,
    height: 54,
    borderRadius: 14,
    backgroundColor: "#F5EEF7",
    alignItems: "center",
    justifyContent: "center",
  },
  dateDay: {
    fontSize: 18,
    fontWeight: "900",
    color: "#6B4F72",
    lineHeight: 20,
  },
  dateMonth: {
    fontSize: 10,
    fontWeight: "800",
    color: MAUVE,
    letterSpacing: 0.5,
  },
  badge: {
    alignSelf: "flex-start",
    backgroundColor: "#F1F5F9",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#475569",
    textTransform: "uppercase",
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0F172A",
    marginTop: 6,
  },
  cardDesc: { fontSize: 13, color: "#64748B", marginTop: 10, lineHeight: 19 },
  metaWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 12 },
  pill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 10,
  },
  pillText: { fontSize: 11, fontWeight: "600", color: "#475569" },
  pillFree: { backgroundColor: "#F0FDF4", borderColor: "#BBF7D0" },
  pillPaid: { backgroundColor: "#FFFBEB", borderColor: "#FDE68A" },
  cardFoot: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 14,
  },
  whenChip: {
    backgroundColor: "#F5EEF7",
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 10,
  },
  whenText: { fontSize: 11, fontWeight: "700", color: MAUVE },
  statusChip: {
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 10,
    backgroundColor: "#F1F5F9",
  },
  statusChipOk: { backgroundColor: "#DCFCE7" },
  statusText: { fontSize: 11, fontWeight: "700", color: "#475569" },
  statusTextOk: { color: "#15803D" },
  action: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 12,
    flexShrink: 1,
  },
  actionText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
    flexShrink: 1,
  },

  // Empty / error
  empty: {
    alignItems: "center",
    paddingVertical: 48,
    paddingHorizontal: 24,
    width: "100%",
  },
  emptyCircle: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: "#F5EEF7",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#0F172A",
    marginTop: 16,
  },
  emptyText: {
    fontSize: 14,
    color: "#64748B",
    textAlign: "center",
    marginTop: 6,
    marginBottom: 20,
    maxWidth: 320,
  },
  cta: {
    backgroundColor: MAUVE,
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 14,
  },
  ctaText: { color: "#FFFFFF", fontWeight: "800", fontSize: 14 },
  errorBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FECACA",
    marginBottom: 14,
  },
  errorText: { flex: 1, fontSize: 13, color: "#991B1B", fontWeight: "500" },
  errorRetry: { fontSize: 13, fontWeight: "800", color: "#DC2626" },
});
