import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  maxContainer: {
    width: "100%",
    maxWidth: 600,
    alignSelf: "center",
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 14,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F1F5F9",
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0F172A",
  },
  headerRightSpacer: {
    width: 36,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 32,
  },
  introCard: {
    backgroundColor: "#DCFCE7",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#86EFAC",
    marginBottom: 20,
  },
  introText: {
    fontSize: 14,
    color: "#14532D",
    lineHeight: 22,
    fontWeight: "500",
  },
  sectorCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    overflow: "hidden",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  sectorImage: {
    width: "100%",
    height: 180,
  },
  sectorContent: {
    padding: 18,
  },
  sectorTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 8,
    lineHeight: 22,
  },
  sectorSubtitle: {
    fontSize: 13,
    color: "#475569",
    lineHeight: 20,
    marginBottom: 14,
  },
  pointsContainer: {
    gap: 10,
    marginTop: 4,
  },
  pointRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingRight: 8,
  },
  bulletPoint: {
    fontSize: 16,
    color: "#16A34A",
    marginRight: 8,
    lineHeight: 20,
  },
  pointText: {
    flex: 1,
    fontSize: 13,
    color: "#334155",
    lineHeight: 20,
  },
  boldText: {
    fontWeight: "700",
    color: "#0F172A",
  },
  bookButton: {
    backgroundColor: "#16A34A",
    paddingVertical: 14,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 10,
    shadowColor: "#16A34A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  bookButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
});
