import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  maxContainer: {
    width: "100%",
    maxWidth: 600,
    alignSelf: "center",
    flex: 1,
  },
  // Top Header Navigation Bar
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 2,
    zIndex: 10,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#0F172A",
    textAlign: "center",
    flex: 1,
    marginHorizontal: 12,
  },
  headerRightAction: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 32,
  },
  // Intro Banner
  introCard: {
    backgroundColor: "#DCFCE7",
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: "#86EFAC",
    marginBottom: 20,
  },
  introBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-start",
    backgroundColor: "rgba(255, 255, 255, 0.6)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 10,
  },
  introBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#15803D",
  },
  bannerTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#14532D",
    marginBottom: 6,
    lineHeight: 24,
  },
  introText: {
    fontSize: 13,
    color: "#166534",
    lineHeight: 20,
    fontWeight: "500",
  },
  // Section Card
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    overflow: "hidden",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  imageWrapper: {
    width: "100%",
    height: 180,
    backgroundColor: "#E2E8F0",
    overflow: "hidden",
  },
  cardImage: {
    width: "100%",
    height: "100%",
  },
  cardContent: {
    padding: 18,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 6,
    lineHeight: 22,
  },
  cardSubtitle: {
    fontSize: 13,
    color: "#64748B",
    lineHeight: 19,
    marginBottom: 14,
  },
  pointsContainer: {
    gap: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
  },
  pointRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingRight: 6,
  },
  bulletDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#16A34A",
    marginTop: 7,
    marginRight: 10,
  },
  pointText: {
    flex: 1,
    fontSize: 13,
    color: "#334155",
    lineHeight: 20,
  },
  boldText: {
    fontWeight: "700",
    color: "#0F172A",
  },
  // Bottom Appointment Button
  bookButton: {
    backgroundColor: "#16A34A",
    paddingVertical: 15,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 8,
    shadowColor: "#16A34A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  bookButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
});
