import { StyleSheet } from "react-native";

const BLUE = "#1E3A8A";

export const ca = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8FAFC" },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 40,
    alignItems: "center",
  },
  content: { width: "100%", maxWidth: 1200 },
  twoCol: { flexDirection: "row", gap: 20, alignItems: "flex-start" },
  colSide: { flex: 1 },
  colMain: { flex: 1.6 },

  // Header
  title: {
    fontSize: 24,
    fontWeight: "900",
    color: "#0F172A",
    letterSpacing: -0.4,
  },
  subtitle: { fontSize: 13, color: "#64748B", marginTop: 2, marginBottom: 16 },

  // Availability card
  calCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: 16,
    marginBottom: 16,
    overflow: "hidden",
  },
  calHead: { flexDirection: "row", alignItems: "center", gap: 12 },
  calIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#FEF2F2",
    alignItems: "center",
    justifyContent: "center",
  },
  calTitle: { fontSize: 15, fontWeight: "800", color: "#0F172A" },
  calSub: { fontSize: 12, color: "#64748B", marginTop: 1 },
  calBody: { marginTop: 12 },
  calHint: { fontSize: 12, color: "#64748B", marginBottom: 8, lineHeight: 17 },

  // Lists
  grid: { flexDirection: "row", flexWrap: "wrap", alignItems: "flex-start" },
  sectionLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: "#64748B",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 10,
  },

  // Session card
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: 16,
    overflow: "hidden",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  cardLate: { borderColor: "#FCD34D" },
  accent: { position: "absolute", left: 0, top: 0, bottom: 0, width: 4 },
  top: { flexDirection: "row", alignItems: "center", gap: 12 },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { fontSize: 14, fontWeight: "800", color: BLUE },
  name: { fontSize: 16, fontWeight: "800", color: "#0F172A" },
  sub: { fontSize: 12, color: "#64748B", marginTop: 2 },
  whenChip: {
    backgroundColor: "#EFF6FF",
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 10,
  },
  whenChipLate: { backgroundColor: "#FEF3C7" },
  whenText: { fontSize: 11, fontWeight: "800", color: BLUE },
  whenTextLate: { color: "#B45309" },

  chips: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 12 },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#F1F5F9",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  chipText: { fontSize: 11, fontWeight: "700", color: "#475569" },

  toggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 12,
    alignSelf: "flex-start",
  },
  toggleText: { fontSize: 12, fontWeight: "800", color: "#2563EB" },

  // Intake
  intake: {
    backgroundColor: "#F8FAFC",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: 12,
    marginTop: 10,
    gap: 10,
  },
  intakeHead: {
    fontSize: 11,
    fontWeight: "800",
    color: "#475569",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  intakeRow: { flexDirection: "row", gap: 8, alignItems: "flex-start" },
  intakeLabel: { fontSize: 12, fontWeight: "700", color: "#334155" },
  intakeValue: { fontSize: 12, color: "#475569", flex: 1, lineHeight: 17 },
  tags: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 4 },
  tag: {
    backgroundColor: "#E0F2FE",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  tagText: { fontSize: 11, fontWeight: "600", color: "#0369A1" },
  paid: {
    backgroundColor: "#DCFCE7",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  paidText: { fontSize: 11, fontWeight: "700", color: "#15803D" },

  // Connect
  connect: { marginTop: 14, gap: 10 },
  linkRow: { flexDirection: "row", gap: 8 },
  linkInput: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 44,
    fontSize: 13,
    color: "#0F172A",
  },
  saveBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#16A34A",
    alignItems: "center",
    justifyContent: "center",
  },
  primary: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    borderRadius: 14,
  },
  primaryText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" },
  phoneBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F0F9FF",
    borderWidth: 1,
    borderColor: "#BAE6FD",
    borderRadius: 12,
    padding: 12,
  },
  phoneText: { fontSize: 13, color: "#0369A1", fontWeight: "500", flex: 1 },

  // Actions
  actions: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 14 },
  action: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  actionText: { fontSize: 12, fontWeight: "800" },

  // History
  hStatus: { fontSize: 12, fontWeight: "800" },
  note: {
    fontSize: 12,
    color: "#334155",
    fontStyle: "italic",
    marginTop: 8,
    lineHeight: 17,
  },
  stars: { flexDirection: "row", gap: 2, marginTop: 6 },

  // Empty
  empty: {
    alignItems: "center",
    paddingVertical: 48,
    paddingHorizontal: 24,
    width: "100%",
  },
  emptyCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0F172A",
    marginTop: 14,
  },
  emptyText: {
    fontSize: 13,
    color: "#64748B",
    textAlign: "center",
    marginTop: 4,
    maxWidth: 300,
  },

  // Modal
  overlay: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.55)",
    justifyContent: "center",
    padding: 20,
  },
  sheet: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 20,
    width: "100%",
    maxWidth: 480,
    alignSelf: "center",
  },
  mHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 14,
  },
  mIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  mTitle: { fontSize: 18, fontWeight: "800", color: "#0F172A", flex: 1 },
  mInput: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: "#0F172A",
    marginBottom: 12,
  },
  mArea: { minHeight: 96, textAlignVertical: "top" },
  mActions: { flexDirection: "row", gap: 10, marginTop: 4 },
  mBtn: {
    flex: 1,
    minHeight: 48,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
});
