import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8FAFC" },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
  },
  headerText: { fontSize: 20, fontWeight: "800", color: "#0F172A" },
  scrollContent: { padding: 20 },

  // Calendar
  calendarCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: 4,
  },
  sectionSub: { fontSize: 12, color: "#64748B", marginBottom: 12 },

  // Sessions
  sessionsSection: { marginBottom: 24 },
  emptyCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  emptyText: { color: "#64748B", marginTop: 8, fontSize: 14 },
  sessionCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: 16,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  badge: {
    backgroundColor: "#EFF6FF",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  badgeText: { fontSize: 12, color: "#1E3A8A", fontWeight: "600" },
  timeText: { fontSize: 12, color: "#64748B" },
  clientName: { fontSize: 17, fontWeight: "700", color: "#0F172A" },
  clientMeta: {
    fontSize: 13,
    color: "#64748B",
    marginTop: 2,
    marginBottom: 12,
  },

  // Link & Call
  linkContainer: { flexDirection: "row", gap: 8, marginBottom: 10 },
  linkInput: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 13,
    height: 40,
    color: "#0F172A",
  },
  saveLinkBtn: {
    backgroundColor: "#16A34A",
    width: 40,
    height: 40,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  joinBtn: {
    backgroundColor: "#1E3A8A",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
    borderRadius: 8,
    gap: 8,
    marginBottom: 14,
  },
  joinBtnText: { color: "#FFFFFF", fontWeight: "600", fontSize: 14 },

  // Action Grid
  actionGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  actionChip: {
    flex: 1,
    minWidth: "45%",
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: "center",
  },
  chipAttended: { backgroundColor: "#DCFCE7" },
  chipTextAttended: { color: "#15803D", fontWeight: "700", fontSize: 12 },
  chipPostpone: { backgroundColor: "#FEF3C7" },
  chipTextPostpone: { color: "#B45309", fontWeight: "700", fontSize: 12 },
  chipTransfer: { backgroundColor: "#E0F2FE" },
  chipTextTransfer: { color: "#0369A1", fontWeight: "700", fontSize: 12 },
  chipCancel: { backgroundColor: "#FEE2E2" },
  chipTextCancel: { color: "#B91C1C", fontWeight: "700", fontSize: 12 },

  // History
  historySection: { marginBottom: 20 },
  historyCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: 10,
  },
  historyHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  historyClient: { fontSize: 15, fontWeight: "700", color: "#0F172A" },
  historyStatus: { fontSize: 12, fontWeight: "700", color: "#16A34A" },
  statusCancelled: { color: "#EF4444" },
  historyMeta: { fontSize: 12, color: "#64748B", marginTop: 2 },
  historyNote: {
    fontSize: 12,
    fontStyle: "italic",
    color: "#334155",
    marginTop: 6,
  },

  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.5)",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: 14,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    marginBottom: 12,
    backgroundColor: "#F8FAFC",
  },
  modalTextArea: { height: 80, textAlignVertical: "top" },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 8,
  },
  cancelBtn: { paddingVertical: 10, paddingHorizontal: 16, borderRadius: 8 },
  cancelBtnText: { color: "#64748B", fontWeight: "600" },
  confirmBtn: {
    backgroundColor: "#16A34A",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  confirmBtnText: { color: "#FFFFFF", fontWeight: "700" },
});
