import { StyleSheet } from "react-native";

const BLUE = "#1E3A8A";

export const cp = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8FAFC" },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 40,
    alignItems: "center",
  },
  content: { width: "100%", maxWidth: 1100 },

  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: "900",
    color: "#0F172A",
    letterSpacing: -0.4,
  },
  subtitle: { fontSize: 13, color: "#64748B", marginTop: 2 },
  newBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#16A34A",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 22,
    shadowColor: "#16A34A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
  },
  newBtnText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" },

  grid: { flexDirection: "row", flexWrap: "wrap", alignItems: "flex-start" },

  // Card
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    overflow: "hidden",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  cardPast: { opacity: 0.9 },
  poster: { width: "100%", height: 130, backgroundColor: "#E2E8F0" },
  body: { padding: 16 },
  head: { flexDirection: "row", gap: 14 },
  dateBlock: {
    width: 50,
    height: 54,
    borderRadius: 14,
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
  },
  dateDay: { fontSize: 18, fontWeight: "900", color: BLUE, lineHeight: 20 },
  dateMonth: {
    fontSize: 10,
    fontWeight: "800",
    color: "#2563EB",
    letterSpacing: 0.5,
  },
  badge: {
    alignSelf: "flex-start",
    backgroundColor: "#F1F5F9",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#475569",
    textTransform: "uppercase",
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0F172A",
    marginTop: 6,
  },
  desc: { fontSize: 13, color: "#64748B", marginTop: 10, lineHeight: 19 },
  meta: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 12 },
  pill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 10,
    maxWidth: "100%",
  },
  pillText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#475569",
    flexShrink: 1,
  },
  pillFree: { backgroundColor: "#F0FDF4", borderColor: "#BBF7D0" },
  pillPaid: { backgroundColor: "#FFFBEB", borderColor: "#FDE68A" },
  foot: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 14 },
  viewBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: BLUE,
    paddingVertical: 11,
    borderRadius: 12,
  },
  viewText: { color: "#FFFFFF", fontSize: 13, fontWeight: "800" },
  iconBtn: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
  },

  // Empty
  empty: {
    alignItems: "center",
    paddingVertical: 48,
    paddingHorizontal: 24,
    width: "100%",
  },
  emptyCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0F172A",
    marginTop: 14,
  },
  emptyText: {
    fontSize: 13,
    color: "#64748B",
    textAlign: "center",
    marginTop: 4,
    marginBottom: 16,
    maxWidth: 300,
  },

  // Modals
  full: { flex: 1, backgroundColor: "#F8FAFC" },
  mHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
  },
  mTitle: { fontSize: 16, fontWeight: "800", color: "#0F172A" },
  mSub: { fontSize: 12, color: "#64748B" },
  mList: { padding: 16, alignItems: "center" },
  mMax: { width: "100%", maxWidth: 640, gap: 12 },
  summary: { flexDirection: "row", gap: 10 },
  sumBox: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: 12,
  },
  sumNum: { fontSize: 20, fontWeight: "900", color: "#0F172A" },
  sumLabel: { fontSize: 12, color: "#64748B", fontWeight: "600" },

  person: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: 14,
  },
  personTop: { flexDirection: "row", alignItems: "center", gap: 10 },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { fontSize: 13, fontWeight: "800", color: BLUE },
  personName: { fontSize: 15, fontWeight: "700", color: "#0F172A" },
  status: {
    alignSelf: "flex-start",
    fontSize: 11,
    fontWeight: "700",
    color: "#B45309",
    backgroundColor: "#FEF3C7",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    marginTop: 3,
    overflow: "hidden",
  },
  statusOk: { color: "#15803D", backgroundColor: "#DCFCE7" },
  details: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
    gap: 6,
  },
  detailRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  detailText: { fontSize: 13, color: "#475569", flex: 1 },
  pActions: { flexDirection: "row", gap: 8, marginTop: 12 },
  pBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingVertical: 9,
    borderRadius: 10,
  },
  pBtnText: { fontSize: 12, fontWeight: "800" },

  // Form
  overlay: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.55)",
    justifyContent: "center",
    padding: 16,
  },
  sheet: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 20,
    maxHeight: "92%",
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
  },
  fTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 14,
  },
  label: {
    fontSize: 13,
    fontWeight: "700",
    color: "#334155",
    marginBottom: 6,
  },
  input: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 11,
    fontSize: 14,
    color: "#0F172A",
    marginBottom: 14,
  },
  inputFocus: { borderColor: BLUE, backgroundColor: "#FFFFFF" },
  area: { height: 88, textAlignVertical: "top" },
  dateBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F8FAFC",
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 14,
  },
  segRow: { flexDirection: "row", gap: 8, marginBottom: 12 },
  seg: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#F1F5F9",
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
  },
  segOn: { backgroundColor: "#16A34A", borderColor: "#16A34A" },
  segText: { fontSize: 13, fontWeight: "700", color: "#64748B" },
  segTextOn: { color: "#FFFFFF" },
  amountRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#F8FAFC",
    marginBottom: 14,
  },
  cur: {
    backgroundColor: "#E2E8F0",
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  curText: { fontSize: 13, fontWeight: "800", color: BLUE },
  amountInput: {
    flex: 1,
    paddingHorizontal: 12,
    fontSize: 14,
    color: "#0F172A",
  },
  posterPick: {
    height: 110,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "#CBD5E1",
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F8FAFC",
    marginBottom: 14,
    gap: 4,
  },
  posterPreview: { width: "100%", height: 170, borderRadius: 14 },
  posterBtns: {
    position: "absolute",
    top: 8,
    right: 8,
    flexDirection: "row",
    gap: 8,
  },
  posterBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(15,23,42,0.75)",
    alignItems: "center",
    justifyContent: "center",
  },
  modCard: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 14,
    padding: 12,
    marginBottom: 12,
  },
  modTitle: { fontSize: 13, fontWeight: "800", color: BLUE, marginBottom: 8 },
  fActions: { flexDirection: "row", gap: 10, marginTop: 8 },
  fBtn: {
    flex: 1,
    minHeight: 48,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
});
