import { StyleSheet } from "react-native";

export const MAUVE = "#936D9A";
const TINT = "#F5EEF7";

export const b = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#FAFAFA" },
  max: { flex: 1, width: "100%", maxWidth: 640, alignSelf: "center" },

  // Header
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 10,
    gap: 12,
  },
  roundBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    alignItems: "center",
    justifyContent: "center",
  },
  headerMid: { flex: 1 },
  headerTitle: { fontSize: 17, fontWeight: "800", color: "#0F172A" },
  headerSub: { fontSize: 12, color: "#64748B", marginTop: 1 },
  track: {
    height: 4,
    marginHorizontal: 16,
    borderRadius: 2,
    backgroundColor: "#E2E8F0",
    overflow: "hidden",
  },
  fill: { height: "100%", borderRadius: 2, backgroundColor: MAUVE },

  // Body
  body: { paddingHorizontal: 20, paddingTop: 22, paddingBottom: 24 },
  title: {
    fontSize: 24,
    fontWeight: "800",
    color: "#0F172A",
    letterSpacing: -0.4,
  },
  subtitle: {
    fontSize: 14,
    color: "#64748B",
    marginTop: 4,
    marginBottom: 20,
    lineHeight: 20,
  },
  groupLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "#334155",
    marginBottom: 10,
    marginTop: 6,
  },
  stack: { gap: 10 },
  gap: { height: 18 },

  // Option card
  option: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
  },
  optionOn: { borderColor: MAUVE, backgroundColor: "#FDF8FF" },
  optionIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
  },
  optionIconOn: { backgroundColor: TINT },
  optionText: { flex: 1 },
  optionTitle: { fontSize: 15, fontWeight: "700", color: "#0F172A" },
  optionSub: { fontSize: 12.5, color: "#64748B", marginTop: 2, lineHeight: 17 },
  tick: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: "#CBD5E1",
    alignItems: "center",
    justifyContent: "center",
  },
  tickOn: { backgroundColor: MAUVE, borderColor: MAUVE },

  // Chips
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
  },
  chipOn: { borderColor: MAUVE, backgroundColor: TINT },
  chipText: { fontSize: 13, fontWeight: "600", color: "#64748B" },
  chipTextOn: { color: MAUVE, fontWeight: "800" },

  // Inputs
  input: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: "#0F172A",
  },
  inputFocus: { borderColor: MAUVE },
  textArea: { minHeight: 110, textAlignVertical: "top" },
  error: {
    color: "#DC2626",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 6,
    marginLeft: 2,
  },
  hint: {
    color: "#64748B",
    fontSize: 12,
    marginTop: 6,
    marginLeft: 2,
    lineHeight: 17,
  },

  // Duration tiles
  tiles: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  tile: {
    flexGrow: 1,
    flexBasis: "47%",
    paddingVertical: 16,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
  },
  tileOn: { borderColor: MAUVE, backgroundColor: "#FDF8FF" },
  tileNum: {
    fontSize: 28,
    fontWeight: "800",
    color: "#0F172A",
    letterSpacing: -0.5,
  },
  tileNumOn: { color: MAUVE },
  tileUnit: { fontSize: 12, fontWeight: "700", color: "#64748B" },
  tileCap: { fontSize: 12, color: "#94A3B8", marginTop: 4 },

  // Counselor
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#E2E8F0",
  },
  avatarFallback: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: TINT,
  },
  exp: { fontSize: 12, fontWeight: "700", color: MAUVE, marginTop: 2 },

  // Dates + slots
  dateStrip: { gap: 8, paddingRight: 20 },
  date: {
    width: 62,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
  },
  dateOn: { borderColor: MAUVE, backgroundColor: MAUVE },
  dateOff: { opacity: 0.4 },
  dateDow: { fontSize: 11, fontWeight: "700", color: "#64748B" },
  dateNum: {
    fontSize: 20,
    fontWeight: "800",
    color: "#0F172A",
    marginVertical: 1,
  },
  dateMon: { fontSize: 11, color: "#94A3B8" },
  dateTextOn: { color: "#FFFFFF" },
  slots: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  slot: {
    paddingVertical: 11,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
  },
  slotOn: { borderColor: MAUVE, backgroundColor: MAUVE },
  slotOff: { backgroundColor: "#F8FAFC", borderColor: "#F1F5F9" },
  slotText: { fontSize: 13, fontWeight: "700", color: "#0F172A" },
  slotTextOn: { color: "#FFFFFF" },
  slotTextOff: { color: "#CBD5E1", textDecorationLine: "line-through" },
  endsAt: { marginTop: 14, fontSize: 13, color: "#475569", fontWeight: "600" },

  // Review
  summary: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 16,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  rowLast: { borderBottomWidth: 0 },
  rowLabel: { fontSize: 13, color: "#64748B" },
  rowValue: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0F172A",
    flexShrink: 1,
    textAlign: "right",
  },
  price: {
    marginTop: 14,
    padding: 16,
    borderRadius: 18,
    backgroundColor: TINT,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  priceLabel: { fontSize: 13, color: "#6B4F72", fontWeight: "600" },
  priceValue: { fontSize: 22, fontWeight: "800", color: "#4A2F52" },
  terms: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginTop: 16,
  },
  termsText: { flex: 1, fontSize: 13, color: "#475569", lineHeight: 19 },
  link: {
    color: "#2563EB",
    fontWeight: "700",
    textDecorationLine: "underline",
  },

  // Footer
  footer: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 12,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
    backgroundColor: "#FFFFFF",
  },
  btn: {
    flex: 1,
    minHeight: 50,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  btnGhost: { flex: 0.7, backgroundColor: "#F1F5F9" },
  btnGhostText: { color: "#475569", fontWeight: "700", fontSize: 15 },
  btnMain: {
    flex: 1.4,
    backgroundColor: MAUVE,
    shadowColor: MAUVE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
  },
  btnMainText: { color: "#FFFFFF", fontWeight: "800", fontSize: 15 },

  // Done
  done: { alignItems: "center", paddingTop: 36 },
  doneCircle: {
    width: 96,
    height: 96,
    borderRadius: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  doneTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#0F172A",
    marginTop: 20,
    textAlign: "center",
  },
  doneText: {
    fontSize: 14,
    color: "#64748B",
    textAlign: "center",
    marginTop: 8,
    marginBottom: 24,
    lineHeight: 21,
    maxWidth: 360,
  },

  // Modal
  overlay: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.55)",
    justifyContent: "center",
    padding: 20,
  },
  modal: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    maxHeight: "80%",
    width: "100%",
    maxWidth: 520,
    alignSelf: "center",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 12,
  },
  modalBody: { fontSize: 13.5, color: "#334155", lineHeight: 21 },
});
